"""
SPICE Netlist Exporter for circuit-synth

Converts circuit-synth Circuit objects to SPICE netlist format.
Maps KiCad symbols to SPICE components with proper net handling.
"""

import logging
from typing import Dict, List, Set

logger = logging.getLogger(__name__)


class SpiceExporter:
    """Export circuit-synth circuits to SPICE netlist format"""
    
    # Component mapping from KiCad symbols to SPICE syntax
    SPICE_COMPONENT_MAP = {
        "Device:R": "R{ref} {pin1} {pin2} {value}",
        "Device:C": "C{ref} {pin1} {pin2} {value}",
        "Device:L": "L{ref} {pin1} {pin2} {value}",
        # Add more component types as needed
    }
    
    def __init__(self, circuit):
        self.circuit = circuit
        self._net_map = {}  # Map net objects to SPICE net names
        
    def generate_netlist(self, include_analysis=True) -> str:
        """
        Generate complete SPICE netlist from circuit-synth circuit.
        
        Args:
            include_analysis: Include basic .DC and .AC analysis commands
            
        Returns:
            str: Complete SPICE netlist ready for simulation
        """
        logger.info(f"Generating SPICE netlist for circuit: {self.circuit.name}")
        
        lines = [
            f"* {self.circuit.name}",
            f"* Generated by circuit-synth SPICE exporter",
            "",
            f".title {self.circuit.name}",
            ""
        ]
        
        # Build net name mapping
        self._build_net_mapping()
        
        # Add components
        lines.append("* Components")
        component_lines = self._export_components()
        lines.extend(component_lines)
        
        # Add voltage sources for analysis (basic implementation)
        if include_analysis:
            lines.extend([
                "",
                "* Voltage sources for analysis",
                "VIN VIN 0 DC 0  ; Sweep this for DC analysis",
                "",
                "* Analysis commands",
                ".DC VIN 0 5 0.1",
                ".AC DEC 10 0.1 1MEG",
                "",
                "* Output requests", 
                ".PRINT DC V(VOUT)",
                ".PRINT AC VDB(VOUT) VP(VOUT)"
            ])
        
        lines.extend(["", ".END"])
        
        netlist = "\n".join(lines)
        logger.info("SPICE netlist generation completed successfully")
        return netlist
    
    def _build_net_mapping(self) -> None:
        """Build mapping from circuit-synth nets to SPICE net names"""
        self._net_map = {}
        
        # Get all nets from the circuit
        nets = self.circuit.get_nets()
        
        for net in nets:
            # Use the net name directly, but sanitize for SPICE
            spice_name = self._sanitize_net_name(net.name)
            self._net_map[net] = spice_name
            
        # Ensure GND/ground net is mapped to "0" (SPICE ground)
        for net in nets:
            if net.name.upper() in ['GND', 'GROUND', 'VSS']:
                self._net_map[net] = "0"
                break
    
    def _sanitize_net_name(self, name: str) -> str:
        """Sanitize net name for SPICE compatibility"""
        # SPICE net names should not have spaces or special characters
        sanitized = name.replace(' ', '_').replace('-', '_')
        # Ensure it doesn't start with a number
        if sanitized[0].isdigit():
            sanitized = 'NET_' + sanitized
        return sanitized
    
    def _export_components(self) -> List[str]:
        """Export all components to SPICE format"""
        component_lines = []
        
        components = self.circuit.get_components()
        
        for comp in components:
            try:
                spice_line = self._component_to_spice(comp)
                if spice_line:
                    component_lines.append(spice_line)
                else:
                    component_lines.append(f"* WARNING: Could not export component {comp.ref} ({comp.symbol})")
            except Exception as e:
                logger.warning(f"Failed to export component {comp.ref}: {e}")
                component_lines.append(f"* ERROR: Failed to export {comp.ref} - {e}")
        
        return component_lines
    
    def _component_to_spice(self, component) -> str:
        """Convert single component to SPICE syntax"""
        symbol = component.symbol
        
        if symbol not in self.SPICE_COMPONENT_MAP:
            logger.warning(f"Unsupported component type: {symbol}")
            return None
        
        # Get the SPICE template for this component type
        template = self.SPICE_COMPONENT_MAP[symbol]
        
        # Get pin connections - this is the tricky part
        pin_nets = self._get_component_pin_nets(component)
        
        if len(pin_nets) < 2:
            logger.warning(f"Component {component.ref} has insufficient pin connections")
            return None
        
        # Format the SPICE line
        return template.format(
            ref=component.ref,
            pin1=pin_nets[0],
            pin2=pin_nets[1] if len(pin_nets) > 1 else "0",
            value=component.value or "1"
        )
    
    def _get_component_pin_nets(self, component) -> List[str]:
        """
        Get SPICE net names for component pins.
        
        This is a simplified implementation - the real one needs to 
        inspect the component's pin connections to nets.
        """
        # TODO: Implement proper pin-to-net mapping
        # For now, return placeholder names based on common patterns
        
        # This is a placeholder - in real implementation, we need to:
        # 1. Get the component's pins
        # 2. Find which nets are connected to each pin  
        # 3. Map those nets to SPICE net names
        
        # Temporary: return some reasonable defaults for testing
        if hasattr(component, '_connected_nets'):
            # If component tracks its net connections
            nets = component._connected_nets
            return [self._net_map.get(net, net.name) for net in nets]
        else:
            # Fallback - return generic names
            # This won't work for real circuits, but allows testing the structure
            return ["VIN", "VOUT"]  # Placeholder for testing
    
    def validate_netlist(self, netlist: str) -> bool:
        """
        Validate generated SPICE netlist for basic correctness.
        
        Returns:
            bool: True if netlist appears valid
        """
        lines = netlist.split('\n')
        
        # Basic validation checks
        has_title = any(line.strip().startswith('.title') for line in lines)
        has_end = any(line.strip() == '.END' for line in lines)
        has_components = any(line.strip() and not line.strip().startswith(('*', '.')) for line in lines)
        
        return has_title and has_end and has_components