[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "kicad"
version = "0.1.0"
description = "High-performance KiCad schematic and PCB manipulation library"
authors = [
    {name = "Shane Mattner", email = "shane@circuit-synth.com"},
]
maintainers = [
    {name = "Circuit-Synth Contributors", email = "shane@circuit-synth.com"},
]
readme = "README.md"
requires-python = ">=3.8"
license = {text = "MIT"}
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Rust",
    "Topic :: Scientific/Engineering :: Electronic Design Automation (EDA)",
    "Topic :: Software Development :: Libraries :: Python Modules",
]
keywords = ["kicad", "eda", "schematic", "pcb", "electronics", "circuit", "design"]
dependencies = []

[project.urls]
Homepage = "https://github.com/circuit-synth/kicad-rust"
Repository = "https://github.com/circuit-synth/kicad-rust"
Documentation = "https://kicad-rust.readthedocs.io"
"Bug Tracker" = "https://github.com/circuit-synth/kicad-rust/issues"
"Source Code" = "https://github.com/circuit-synth/kicad-rust"

[project.optional-dependencies]
dev = [
    "pytest>=7.0",
    "pytest-cov>=4.0",
    "black>=23.0",
    "ruff>=0.1",
    "mypy>=1.0",
]
docs = [
    "sphinx>=6.0",
    "sphinx-rtd-theme>=1.3",
    "sphinx-autodoc-typehints>=1.23",
]

[tool.maturin]
module-name = "kicad._rust"
features = ["python"]
bindings = "pyo3"
python-source = "python"
include = [
    "Cargo.toml",
    "src/**/*.rs",
    "README.md",
    "LICENSE*",
]

[tool.ruff]
line-length = 100
target-version = "py38"

[tool.black]
line-length = 100
target-version = ["py38"]

[tool.mypy]
python_version = "3.8"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true